name: Testing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.12, 1.17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt




