
name: Build and Test

on:
  push:
  pull_request:
  repository_dispatch:
  schedule:
     - cron: '05 5 1 * *' # <https://crontab.guru/#05_5_1_*_*> - "At 05:05 on day-of-month 1"  


jobs:

  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Go environment
      uses: actions/setup-go@v5.1.0
      with:
          go-version: '1.21.13'
    
    - name: Build
      run: go build -v ./...
    
    - name: test
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
